name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: decrypt
      run: |
        mkdir $HOME/secrets
        gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" \
        --output $HOME/secrets/key google_compute_engine.gpg
      env:
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
    - name: chmod
      run: chmod 600 $HOME/secrets/key
#    - name: git pull
#      run: ssh -o StrictHostKeyChecking=no -i $HOME/secrets/key zen_master@35.187.152.88 "cd postmark-side-project/;git pull;sudo /home/zen_master/.nvm/versions/node/v10.15.3/bin/npm install;sudo /home/zen_master/.nvm/versions/node/v10.15.3/bin/pm2 reload ecosystem.config.js"
#      run: ssh -o StrictHostKeyChecking=no -i $HOME/secrets/key zen_master@35.187.152.88 -tt "bash -l -c "cd postmark-side-project/;sudo /usr/bin/git pull dev;sudo npm install;bash""
#      run: ssh -o StrictHostKeyChecking=no -i $HOME/secrets/key zen_master@35.187.152.88 -tt "bash -l -c "cd test2/postmark-side-project/;git pull;bash"" # Warning: Permanently added '35.187.152.88' (ECDSA) to the list of known hosts.
#      run: ssh -o StrictHostKeyChecking=no -i $HOME/secrets/key zen_master@35.187.152.88 "export PATH=$PATH:/home/zen_master/.nvm/versions/node/v10.15.3/bin;source /home/zen_master/.bashrc;echo $PATH"     
#      run: ssh -o StrictHostKeyChecking=no -i $HOME/secrets/key zen_master@35.187.152.88 "cd test2/postmark-side-project/;git pull"
    - name: npm install
      run: ssh -o StrictHostKeyChecking=no -i $HOME/secrets/key zen_master@35.187.152.88 -tt "bash -l -c "cd test_npm/;npm install pm2;bash""
      